version: '3'

services:
  cosmo-bot:
    container_name: CosmoBotGpt
    working_dir: /.
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mysql_db
    command: sh -c "python main.py" 
  cosmo-server:
    container_name: CosmoBotGpt-server
    working_dir: /.
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - mysql_db
    build:
        context: .
        dockerfile: Dockerfile
    command: "gunicorn server:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
  mysql_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=root_pass
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
