
version: "3.11"

services:
  telegram-bot:
    container_name: telegram-bot
    working_dir: /.
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "python main.py" "python server.py"