version: '3'

services:
  
  cosmo-bot:
    container_name: CosmoBotGpt
    working_dir: /.
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mysql_db
    networks:
      - cosmogpt_default
      - openai_v1_bot_default
    command: sh -c "python main.py" 
    links:
      - mysql_db


  cosmo-server:
    container_name: CosmoBotGpt-server
    working_dir: /.
    restart: always
    # ports:
    #   - "8000:8000"
    networks:
      - cosmogpt_default
      - openai_v1_bot_default
    depends_on:
      - mysql_db
    build:
        context: .
        dockerfile: Dockerfile
    command: "python server.py"
    links:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: cosmogpt
      MYSQL_USER: bot
      MYSQL_PASSWORD: hidden_pass
    # ports:
    #   - '3306:3306'
    networks:
      - cosmogpt_default
      # - openai_v1_bot_default
    # command: --init-file /data/application/init.sql
    volumes:
      - /var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_db:
    driver: local

networks:
  cosmogpt_default:
    external: true
  
  openai_v1_bot_default:
    external: true

          