version: '3'

services:
  cosmo-bot:
    container_name: CosmoBotGpt
    working_dir: /.
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "python main.py" 
  cosmo-server:
    container_name: CosmoBotGpt-server
    working_dir: /.
    restart: always
    ports:
      - "80:8000"
    build:
        context: .
        dockerfile: Dockerfile
    command: "gunicorn server:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
  mysql_db:
    build:
      context: .
      dockerfile: app-db/Dockerfile

    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=Optimize
    ports:
      - 3306:3306
