version: '3'

services:
  
  cosmo-bot:
    container_name: CosmoBotGpt
    working_dir: /.
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mysql_db
    command: sh -c "python main.py" 
  
  cosmo-server:
    container_name: CosmoBotGpt-server
    working_dir: /.
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - mysql_db
    build:
        context: .
        dockerfile: Dockerfile
    command: "python server.py"
  
  mysql_db:
    image: mariadb
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: cosmogpt
      MYSQL_USER: bot
      MYSQL_PASSWORD: hidden_pass
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  openai_v1_bot_default:
    external: true