

services:
  telegram-bot:
    container_name: CosmoBot
    working_dir: /.
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: sh -c "python main.py" "python server.py"